better error message when mv fails

diff --git a/bin/rename_lsb_acct_file b/bin/rename_lsb_acct_file
--- a/bin/rename_lsb_acct_file
+++ b/bin/rename_lsb_acct_file
@@ -41,8 +41,11 @@ for f in "$@"; do
 	newname="lsb.acct.$(date +%Y%m%d%H%M%S -d @$(head -n 1 "$f" | awk '{print $3}'))"-"$(date +%Y%m%d%H%M%S -d @$(tail -n 1 "$f" | awk '{print $3}'))"
 	if echo "$newname" | grep -qP 'lsb.acct.\d{14}-\d{14}'; then
 		mv -i -v "$f" "$newname"  #(want to use mv -n, but not all versions have that)
-	else:
-		echo "*** ERROR *** unable to rename [$f], skipping" >&2
+		if [ $? -ne 0 ]; then
+			echo "*** ERROR *** error renaming [$f], skipping" >&2
+		fi
+	else
+		echo "*** ERROR *** unable to come up with new name for [$f], skipping" >&2
 	fi
 	echo
 done
